name: API Test Automation with TypeScript and Cypress

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 0 20 * * 6

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Run Cypress tests
      run: npx cypress run
    - name: Run Cypress Merge results
      run: npm run mochawesome-merge
    - name: Run Cypress Generate HTML report
      run: npm run mochawesome-report-generator
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: cypress-report
        path: mochawesome-report/
        retention-days: 30
